apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: amandamariano
  name: project2-pv-amandamariano
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi